name: flutter_esptouch_smartconfig
description: "A new Flutter package project."
version: 2.3.2
homepage:

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.ziyou.esptouch_smartconfig
        pluginClass: EsptouchSmartconfigPlugin
      ios:
        pluginClass: EsptouchSmartconfigPlugin